package exception;

public class Exception {
    public static void main(String[] args) {
        int y = 1;
        int x = 1;

        // try block to 'SEE' if an exception occurs
        try {
            int z = x / y; // This will cause an ArithmeticException
            System.out.println("After Division");
        }
        // Catch block handles the ArithmeticException generated by division by zero
        catch (ArithmeticException ae) {
            System.out.println("Attempt to divide by 0");
        }

        System.out.println("After catch");
    }
}
